name: Continuous Integration tests

on: ["pull_request", "push"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pytest
        run: PYTHONPATH=./features/ pytest -s test/*
