name: Continuous Integration tests

on: ["pull_request", "push"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: run test
        run: PYTHONPATH=./features/ pytest -s test/*
